#!/bin/sh
echo "Content-type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html lang='en' class=''>"
echo "  <head>"
echo "    <title>YaCAM Factory Reset</title>"
echo "    <meta charset='utf-8'>"
echo "  </head>"
echo "  <body>"
echo "    <div style='text-align:left;display:inline-block;color:#000000;min-width:340px;'>"
echo "      <h1>YaCAM Factory Reset!</h1>"
echo "      <p></p>"
echo "      <p>After the factory reset connect to the YACAM access point to configure the device!</p>"
echo "    </div>"
echo "  </body>"
echo "</html>"
rm /config/overlay/etc/yacam.conf
/sbin/reboot
