#!/bin/sh

# load current variables
. /etc/yacam.conf

read QUERY_STRING
eval $(echo "$QUERY_STRING"|awk -F'&' '{for(i=1;i<=NF;i++){print $i}}')
WFNAME=`httpd -d $WIFINAME`
WFPSK=`httpd -d $WIFIPSK`
WHIDDEN=`httpd -d $WHIDDEN`
NNTPSERVER=`httpd -d $NNTPSERVER`
NTIMEZONE=`httpd -d $NTIMEZONE`
NFLIP_VERTICAL=`httpd -d $NFLIP_VERTICAL`
NFLIP_HORIZONTAL=`httpd -d $NFLIP_HORIZONTAL`
NTIME_LOCATION=`httpd -d $NTIME_LOCATION`
NTIMESTAMP=`httpd -d $NTIMESTAMP`
NTIME_24=`httpd -d $NTIME_24`
NENABLE_MAIN_RTSP=`httpd -d $NENABLE_MAIN_RTSP`
NENABLE_MJPEG=`httpd -d $NENABLE_MJPEG`
NENABLE_SUB_RTSP=`httpd -d $NENABLE_SUB_RTSP`
NENABLE_AUTH=`httpd -d $NENABLE_AUTH`
NUSERNAME=`httpd -d $NUSERNAME`
NPASSWORD=`httpd -d $NPASSWORD`
WWIFIMAC=`httpd -d $WWIFIMAC`
NHTTPPROT=`httpd -d $NHTTPPROT`
NHTTPPWD=`httpd -d $NHTTPPWD`
NHTTPUSER=`httpd -d $NHTTPUSER`
NAUTONIGHT=`httpd -d $NAUTONIGHT`
NIRLED=`httpd -d $NIRLED`
NHOSTNAME=`httpd -d $NHOSTNAME`
echo "Content-type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html lang='en' class=''>"
echo "  <head>"
echo "    <title>YaCAM Setup Save</title>"
echo "    <meta charset='utf-8'>"
echo "    <meta http-equiv=Refresh Content='5; Url=/'>"
echo "    <meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'/>"
echo "    <style>div,fieldset,input,select{padding:5px;font-size:1em;}fieldset{background:#f2f2f2;}p{margin:0.5em 0;}input{width:100%;box-sizing:></style>"
echo "  </head>"
echo "  <body>"
echo "    <div style='text-align:left;display:inline-block;color:#000000;min-width:340px;'>"
echo "      <h1>YaCAM Setup Save</h1>"
echo "      <p> Saving settings<p>"
echo "      <p></p>"
echo "      <div></div>"

if [ "$NHOSTNAME" != "$HOSTNAME" ]
then
	echo $NHOSTNAME > /tmp/hostname
        sed -i "/HOSTNAME/c\HOSTNAME=$NHOSTNAME" /etc/yacam.conf
	/bin/hostname -F /tmp/hostname
        echo "      <p>HOSTNAME Saved</p>"
fi
WIFIRESTART=0
if [ "$WFNAME" != "$NETNAME" ]
then
	sed -i "/NETNAME/c\NETNAME=$WFNAME" /etc/yacam.conf
	WIFIRESTART=1
	echo "      <p>SSID Saved</p>"
fi
if [ "$WFPSK" != "$NETPW" ]
then
	sed -i "/NETPW/c\NETPW=$WFPSK" /etc/yacam.conf
        WIFIRESTART=1
	echo "      <p>WIFI Password Saved</p>"
fi
if [ "$WHIDDEN" != "$HIDDEN" ]
then
        sed -i "/HIDDEN/c\HIDDEN=$WHIDDEN" /etc/yacam.conf
        WIFIRESTART=1
        echo "      <p>Hidden SSID Saved</p>"
fi
if [ "$WWIFIMAC" != "$WIFI_MAC" ]
then
        sed -i "/WIFI_MAC/c\WIFI_MAC=$WWIFIMAC" /etc/yacam.conf
        WIFIRESTART=1
        echo "      <p>WIFI MAC Saved</p>"
fi

NTPRESTART=0
if [ "$NNTPSERVER" != "$NTPSERVER" ]
then
	sed -i "/NTPSERVER/c\NTPSERVER=$NNTPSERVER" /etc/yacam.conf
	NTPRESTART=1
	echo "      <p>NTP Server saved</p>"ű
fi
if [ "$NTIMEZONE" != "$TIMEZONE" ]
then
        sed -i "/TIMEZONE/c\TIMEZONE=$NTIMEZONE" /etc/yacam.conf
        NTPRESTART=1
        echo "      <p>Timezone saved</p>"
fi

HTTPRESTART=0
if [ "$NHTTPPROT" != "$HTTPPROT" ]
then
        sed -i "/HTTPPROT/c\HTTPPROT=$HTTPPROT" /etc/yacam.conf
        HTTPRESTART=1
        echo "      <p>HTTP Server saved</p>"
fi
if [ "$NHTTPUSER" != "$HTTPUSER" ]
then
        sed -i "/HTTPUSER/c\HTTPUSER=$NHTTPUSER" /etc/yacam.conf
        HTTPRESTART=1
        echo "      <p>Admin USERNAME updated</p>"
fi
if [ "$NHTTPPWD" != "$HTTPPWD" ]
then
        sed -i "/HTTPPWD/c\HTTPPWD=$NHTTPPWD" /etc/yacam.conf
        HTTPRESTART=1
        echo "      <p>Admin PASSWORD updated</p>"
fi
CAPTURERESTART=0
if [ "$NFLIP_VERTICAL" != "$FLIP_VERTICAL" ]
then
        sed -i "/FLIP_VERTICAL/c\FLIP_VERTICAL=$NFLIP_VERTICAL" /etc/yacam.conf
        CAPTURERESTART=1
        echo "      <p>Flip Vertical saved</p>"
fi
if [ "$NFLIP_HORIZONTAL" != "$FLIP_HORIZONTAL" ]
then
        sed -i "/FLIP_HORIZONTAL/c\FLIP_HORIZONTAL=$NFLIP_HORIZONTAL" /etc/yacam.conf
        CAPTURERESTART=1
        echo "      <p>Flip Horizontal saved</p>"
fi
if [ "$NTIME_LOCATION" != "$TIME_LOCATION" ]
then
        sed -i "/TIME_LOCATION/c\TIME_LOCATION=$NTIME_LOCATION" /etc/yacam.conf
        CAPTURERESTART=1
        echo "      <p>Time Stamp Location saved</p>"
fi
if [ "$NTIMESTAMP" != "$TIMESTAMP" ]
then
        sed -i "/TIMESTAMP/c\TIMESTAMP=$NTIMESTAMP" /etc/yacam.conf
        CAPTURERESTART=1
        echo "      <p>Timestamp saved</p>"
fi
if [ "$NTIME_24" != "$TIME_24" ]
then
        sed -i "/TIME_24/c\TIME_24=$NTIME_24" /etc/yacam.conf
        CAPTURERESTART=1
        echo "      <p>Time 24 saved</p>"
fi
RTSPRESTART=0
if [ "$NENABLE_MAIN_RTSP" != "$ENABLE_MAIN_RTSP" ]
then
        sed -i "/ENABLE_MAIN_RTSP/c\ENABLE_MAIN_RTSP=$NENABLE_MAIN_RTSP" /etc/yacam.conf
        RTSPRESTART=1
        echo "      <p>RTSP Main updated</p>"
fi
if [ "$NENABLE_SUB_RTSP" != "$ENABLE_SUB_RTSP" ]
then
        sed -i "/ENABLE_SUB_RTSP/c\ENABLE_SUB_RTSP=$NENABLE_SUB_RTSP" /etc/yacam.conf
        RTSPRESTART=1
        echo "      <p>RTSP Sub updated</p>"
fi
MJPEGRESTART=0
if [ "$NENABLE_MJPEG" != "$ENABLE_MJPEG" ]
then
        sed -i "/ENABLE_MJPEG/c\ENABLE_MJPEG=$NENABLE_MJPEG" /etc/yacam.conf
        MJPEGSTART=1
        echo "      <p>MJPEG updated</p>"
fi
if [ "$NENABLE_AUTH" != "$ENABLE_AUTH" ]
then
        sed -i "/ENABLE_AUTH/c\ENABLE_AUTH=$NENABLE_AUTH" /etc/yacam.conf
        RTSPRESTART=1
	MJPEGSTART=1
        echo "      <p>AUTH updated</p>"
fi
if [ "$NUSERNAME" != "$USERNAME" ]
then
        sed -i "/USERNAME/c\USERNAME=$NUSERNAME" /etc/yacam.conf
        RTSPRESTART=1
        MJPEGSTART=1
        echo "      <p>USERNAME updated</p>"
fi
if [ "$NPASSWORD" != "$PASSWORD" ]
then
        sed -i "/PASSWORD/c\PASSWORD=$NPASSWORD" /etc/yacam.conf
        RTSPRESTART=1
        MJPEGSTART=1
        echo "      <p>PASSWORD updated</p>"
fi
NIGHTRESTART=0
if [ "$NAUTONIGHT" != "$ENABLE_AUTONIGHT" ]
then
        sed -i "/ENABLE_AUTONIGHT/c\ENABLE_AUTONIGHT=$NAUTONIGHT" /etc/yacam.conf
        NIGHTRESTART=1
        echo "      <p>AUTONIGHT updated</p>"
fi
if [ "$NIRLED" != "$ENABLE_IR_LED" ]
then
        sed -i "/ENABLE_IR_LED/c\ENABLE_IR_LED=$NIRLED" /etc/yacam.conf
        NIGHTRESTART=1
        echo "      <p>IR LED Updated updated</p>"
fi
echo "      <p>Settings saved! Restarting services</p>"
sleep 1

if [ "$WIFIRESTART" = "1" ]
then
	echo "      <p>Restaring WiFi!"
	/etc/init.d/S30wifi restart > /dev/null
        echo " Done!</p>"
fi
if [ "$NTPRESTART" = "1" ]
then
        echo "      <p>Restaring NTP!"
        /etc/init.d/S45ntpd restart > /dev/null
        echo " Done!</p>"
fi
if [ "$HTTPRESTART" = "1" ]
then
	echo "      <p>Restaring HTTPD!"
	/etc/init.d/S50httpd restart > /dev/null
	echo " Done!</p>"
fi
if [ "$CAPTURERESTART" = "1" ]
then
        echo "      <p>Restaring Capture!"
        /etc/init.d/S62capture stop > /dev/null
	/etc/init.d/S60capturesettings restart > /dev/null
	/etc/init.d/S62capture start > /dev/null
        echo " Done!</p>"
fi
if [ "$RTSPRESTART" = "1" ]
then
        echo "      <p>Restaring RTSP!"
        /etc/init.d/S64v4l2rtpserver restart > /dev/null
        echo " Done!</p>"

fi
if [ "$MJPEGRESTART" = "1" ]
then
        echo       "<p>Restaring MJPEG!"
        /etc/init.d/S66mjpg_streamer restart > /dev/null
        echo " Done!</p>"
fi
if [ "$NIGHTRESTART" = "1" ]
then
        echo       "<p>Restaring Autonight!"
        /etc/init.d/S70autonight restart > /dev/null
        echo " Done!</p>"
fi

echo "      <p>Returning to main page in a few seconds!</p>"
echo "      <p></p>"
echo "    </div>"
echo "  </body>"
echo "</html>"
