#!/bin/sh

# POST upload format:
# -----------------------------29995809218093749221856446032^M
# Content-Disposition: form-data; name="file1"; filename="..."^M
# Content-Type: application/octet-stream^M
# ^M    <--------- headers end with empty line
# file contents
# file contents
# file contents
# ^M    <--------- extra empty line
# -----------------------------29995809218093749221856446032--^M

echo "Content-type: text/html"
echo
echo "<!DOCTYPE html>"
echo "<html lang='en' class=''>"
echo "  <head>"
echo "    <title>YaCAM Firmware Update</title>"
echo "    <meta charset='utf-8'>"
echo "    <meta http-equiv=Refresh Content='10; Url=/'>"
echo "    <style> body { white-space: pre; } </style>"
echo "  </head>"
echo "  <body>"

file=/tmp/yacam_ota.tar

CR=`printf '\r'`

# CGI output must start with at least empty line (or headers)
printf '\r\n'

IFS="$CR"
read -r delim_line
IFS=""

while read -r line; do
    test x"$line" = x"" && break
    test x"$line" = x"$CR" && break
done

cat >"$file"

# We need to delete the tail of "\r\ndelim_line--\r\n"
tail_len=$((${#delim_line} + 6))

# Get and check file size
# filesize=`stat -c"%s" "$file"`
filesize=`wc -c "$file" | awk '{print $1}'`

test "$filesize" -lt "$tail_len" && exit 1

# Check that tail is correct
dd if="$file" skip=$((filesize - tail_len)) bs=1 count=1000 >"$file.tail" 2>/dev/null
printf "\r\n%s--\r\n" "$delim_line" >"$file.tail.expected"

if ! diff -q "$file.tail" "$file.tail.expected" >/dev/null; then
    echo "<p>Malformed file upload</p></body></html>"
    exit 1
fi
rm "$file.tail"
rm "$file.tail.expected"

# Truncate the file
dd of="$file" seek=$((filesize - tail_len)) bs=1 count=0 >/dev/null 2>/dev/null

echo "<p>File upload has been accepted</p>"
echo "    <textarea id='firm' name='firm' rows='40' cols='80' readonly>"

/usr/bin/upgrade_yacam.sh "www" "$file" "y"

echo "    </textarea>"
echo "  </body>"
echo "</html>"

