#!/bin/sh

set -a
. /etc/yacam.conf
VERSION=`cat /etc/VERSION`

case $HIDDEN in
        0)
                HID0=' selected'
                ;;
        1)
                HID1=' selected'
                ;;
        *)
                ;;
esac
case $WIFI_MAC in
        0)
                WMC0=' selected'
                ;;
        1)
                WMC1=' selected'
                ;;
        *)
                ;;
esac

set +a

envsubst < /var/wwwap/wwwtpl/WifiSetup.tpl
