#!/bin/sh
#
# Start logging
#

start() {
	printf "Starting logging: "
	start-stop-daemon -b -S -q -m -p /tmp/syslogd.pid --exec /sbin/syslogd -- -n
	start-stop-daemon -b -S -q -m -p /tmp/klogd.pid --exec /sbin/klogd -- -n
	echo "OK"
}

stop() {
	printf "Stopping logging: "
	start-stop-daemon -K -q -p /tmp/syslogd.pid
	start-stop-daemon -K -q -p /tmp/klogd.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
