#!/bin/sh
#
# Start the wifi....
#

# Set default WIFI_MODULE
# WIFI_MODULE=8189fs

. /etc/yacam.conf

case "$1" in
  start)

	logger -s "Starting wifi using module $WIFI_MODULE" 
	WIFI_PARAM=""
	if [[ $WIFI_MAC == "1" ]]; then
		mount -t jffs2 /dev/mtdblock5 /params
		MAC=`grep MAC < /params/config/.product_config | cut -c16-27 | sed 's/\(..\)/\1:/g;s/:$//'`
		if [ "$MAC" != "" ]; then
			WIFI_PARAM="rtw_initmac=$MAC"
		fi
		umount /params
	fi
	modprobe $WIFI_MODULE $WIFI_PARAM

	CONFIGPATH="/etc"

	# Create wpa_supplicant.conf
	echo "network={" > /tmp/wpa_supplicant.conf
	echo "    ssid=\"$NETNAME\"" >> /tmp/wpa_supplicant.conf
	echo "    priority=1" >> /tmp/wpa_supplicant.conf
	echo "    key_mgmt=WPA-PSK" >> /tmp/wpa_supplicant.conf
	echo "    psk=\"$NETPW\"" >> /tmp/wpa_supplicant.conf
	echo "    mode=$HIDDEN" >> /tmp/wpa_supplicant.conf
	echo "}" >> /tmp/wpa_supplicant.conf

	ADDITIONAL_FLAGS=""
	if [ "$ENABLE_LOGGING" == "1" ]; then
		ADDITIONAL_FLAGS="-f /var/log/wpa_supplicant.log"
	fi

	wpa_supplicant -P /tmp/wpa.pid -Dnl80211 -i wlan0 -c "/tmp/wpa_supplicant.conf" -B -d $ADDITIONAL_FLAGS

	HOSTNAME=`cat /etc/hostname`

	# wait for connection
	I=0
	while [ "`cat /sys/class/net/wlan0/operstate`" != "up" ] && [[ $I -lt 5 ]]
	do
		I=$((I+1))
		echo "Waiting for WiFi connection..."
		sleep 1
	done

	# Handle if not connected to wifi, start AP and reboot in 5 minutes
        if [ "`cat /sys/class/net/wlan0/operstate`" != "up" ]
        then
                kill `cat /tmp/wpa.pid`
                # Setup AP
                APNAME="YaCAM"`cat /sys/class/net/wlan0/address | sed -r 's/[:]+//g'`
                rm /tmp/wpa_supplicant.conf
                echo "interface=wlan0" > /tmp/ap.conf
                echo "ssid=$APNAME" >> /tmp/ap.conf
                echo "channel=6" >> /tmp/ap.conf
                echo "driver=nl80211" >> /tmp/ap.conf
                # Reboot in 5 minutes in case this is only a temporary failure
                `sleep 300 ; reboot` &
                hostapd -B -t -d /tmp/ap.conf >> /tmp/hostapd.log
                # Set IP Address
                ip addr add 192.168.4.1/24 dev wlan0
                # Start DHCP Server
                udhcpd -I 192.168.4.1 /etc/dhcpservap.conf
                # Create DNS to resolve everything to 192.168.4.1
                echo "* 192.168.4.1" > /tmp/dnsd.conf
                dnsd -d -c /tmp/dnsd.conf
        else
                logger -s "Using hostname: $HOSTNAME"
                logger -s "Attempting DHCP"

                # -i Interface wlan0
                # -b Background if lease is not obtained
                # -A 20 Wait if lease is not obtained in 20 seconds
                # -S Log to syslog
                # -t 5 Send up to 5 discover packets (default 3)
                # -n exit if lease is not obtained

		udhcpc -p /tmp/udhcpc.pid -i wlan0 -b -A 10 -S -t 10 -n -x hostname:$HOSTNAME
		ifconfig | logger -s
		# TODO: What to do if DHCP fails?
        fi
	;;
  stop)
	printf "Stopping wifi..."
        kill `cat /tmp/wpa.pid`
        kill `cat /tmp/udhcpc.pid`
        rm /tmp/udhcpc.pid
        rm /tmp/wpa.pid
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
