#!/bin/sh
#
# Start the wifi....
#

# Set default WIFI_MODULE
WIFI_MODULE=8189fs

. /etc/yacam.conf

case "$1" in
  start)

	logger -s "Starting wifi using module $WIFI_MODULE" 

	modprobe $WIFI_MODULE

	CONFIGPATH="/etc"

	# Create wpa_supplicant.conf
	echo "network={" > /tmp/wpa_supplicant.conf
	echo "    ssid=\"$NETNAME\"" >> /tmp/wpa_supplicant.conf
	echo "    priority=2" >> /tmp/wpa_supplicant.conf
	echo "    key_mgmt=WPA-PSK" >> /tmp/wpa_supplicant.conf
	echo "    psk=\"$NETPW\"" >> /tmp/wpa_supplicant.conf
	echo "}" >> /tmp/wpa_supplicant.conf

	wpa_supplicant -P /tmp/wpa.pid -Dnl80211 -i wlan0 -c "/tmp/wpa_supplicant.conf" -B -d -f /var/log/wpa_supplicant.log

	HOSTNAME=`cat /etc/hostname`

	# wait for connection
	I=0
	while [[ `cat /sys/class/net/wlan0/carrier` -eq "0" ]] && [[ $I -lt 5 ]]
	do
		I=$((I+1))
		sleep 1
	done

	# Handle if not connected to wifi, start AP and reboot in 5 minutes
	if [[ `cat /sys/class/net/wlan0/carrier` -eq "0" ]]
	then
		kill `cat /tmp/wpa.pid`
		# Setup AP
		APNAME="YaCAM"`cat /sys/class/net/wlan0/address | sed -r 's/[:]+//g'`
		rm /tmp/wpa_supplicant.conf
		echo "network={" > /tmp/ap.conf
		echo "    ssid=\"$APNAME\"" >> /tmp/ap.conf
		echo "    mode=2" >> /tmp/ap.conf
		echo "    key_mgmt=NONE" >> /tmp/ap.conf
		echo "    frequency=2437" >> /tmp/ap.conf
		echo "}" >> /tmp/ap.conf
		# Reboot in 5 minutes in case this is only a temporary failure
		`sleep 300 ; reboot` &
		wpa_supplicant -Dnl80211 -i wlan0 -c "/tmp/ap.conf" -B -d -f /var/log/wpa_supplicant.log
		# Set IP Address
		ip addr add 192.168.4.1/24 dev wlan0
		# Start DHCP Server
		udhcpd -I 192.168.4.1 /etc/dhcpservap.conf
	else
		logger -s "Using hostname: $HOSTNAME"
		logger -s "Attempting DHCP"

		# -i Interface wlan0
		# -b Background if lease is not obtained
		# -A 20 Wait if lease is not obtained in 20 seconds
		# -S Log to syslog
		# -t 5 Send up to 5 discover packets (default 3)
		# -n exit if lease is not obtained

		udhcpc -p /tmp/udhcpc.pid -i wlan0 -b -A 10 -S -t 10 -n -x hostname:$HOSTNAME
		ifconfig | logger -s
	fi

	;;
  stop)
	printf "Stopping wifi..."
        kill `cat /tmp/wpa.pid`
        kill `cat /tmp/udhcpc.pid`
        rm /tmp/udhcpc.pid
        rm /tmp/wpa.pid
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
