#!/bin/sh
#
# Start network time daemon
#

case "$1" in
  start)
	if [[ -f /tmp/ap.conf ]]
	then
		echo "AP Mode Not Starting"
		exit
	fi
        if [[ -f /etc/yacam.conf ]]; then
                set -a
                . /etc/yacam.conf
                set +a
        else
                echo "No config"
		TIMEZONE="America/New York"
                NTPSERVER=time.google.com
        fi
	logger -s "Starting ntpd: "
	echo "$TIMEZONE" > /tmp/timezone

        TZONE=$(grep -i -F "$TIMEZONE" /var/www/js/tz.js)
        if [ -z "$TZ" ]; then
                warn "Timezone $TIMEZONE not found!"
        fi

        TZ=$(echo "$TZONE" | sed "s/^.*v:'\([^']*\)'.*$/\1/")
        export TZ
	echo "$TZ" > /tmp/TZ

	#echo "server $NTPSERVER" >> /tmp/ntp.conf
	/usr/sbin/ntpd -p $NTPSERVER
	[ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
	;;
  stop)
	logger -s "Stopping ntpd: "
	killall ntpd
	[ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

