#!/bin/sh
#
# Starts busybox httpd.
#

start() {
        echo "Starting busybox httpd server...."
        if [[ -f /tmp/ap.conf ]]
        then
                # AP mode
                echo "AP Mode"
		echo "E404:404.html" > /tmp/httpd.conf
		httpd -h /var/wwwap -p 80 -v -c /tmp/httpd.conf
        else
		. /etc/yacam.conf
		PARAM=""
		if [ "$HTTPPROT" == "1" ]
		then
			echo "/:$HTTPUSER:"`httpd -m $HTTPPWD` > /tmp/httpd.conf
			PARAM=" -c /tmp/httpd.conf"
		fi
                # Normal mode
                echo "Normal Mode"
                httpd -h /var/www -p 80 -v $PARAM
        fi
        echo "OK"
}
stop() {
        echo "Stopping busybox httpd server..."
        killall httpd
	rm /tmp/httpd.conf
        echo "Done"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

