#!/bin/sh
#
# Start script that monitors the reset button
# If it held down for longer than 6 seconds it will wipe /config
#

case "$1" in
  start)
        if [[ -f /tmp/ap.conf ]]
        then
                echo "AP Mode Not Starting"
                exit
        fi
	logger -s -t network_monitor "Starting network monitor"
	/usr/bin/network_monitor.sh > /dev/null 2>&1 &
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	logger -s -t network_monitor "Stopping network monitor"
	killall network_monitor.sh
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
